# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(507, 267)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ConnectProverka = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectProverka.setObjectName("ConnectProverka")
        self.horizontalLayout.addWidget(self.ConnectProverka)
        self.SaveSetting = QtWidgets.QPushButton(self.centralwidget)
        self.SaveSetting.setObjectName("SaveSetting")
        self.horizontalLayout.addWidget(self.SaveSetting)
        self.SelectRepository = QtWidgets.QPushButton(self.centralwidget)
        self.SelectRepository.setObjectName("SelectRepository")
        self.horizontalLayout.addWidget(self.SelectRepository)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineNameDB = QtWidgets.QLineEdit(self.centralwidget)
        self.lineNameDB.setObjectName("lineNameDB")
        self.gridLayout_2.addWidget(self.lineNameDB, 3, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 3, 1, 1, 1)
        self.linePassword = QtWidgets.QLineEdit(self.centralwidget)
        self.linePassword.setObjectName("linePassword")
        self.gridLayout_2.addWidget(self.linePassword, 1, 0, 1, 2)
        self.lineNameUser = QtWidgets.QLineEdit(self.centralwidget)
        self.lineNameUser.setObjectName("lineNameUser")
        self.gridLayout_2.addWidget(self.lineNameUser, 0, 0, 1, 2)
        self.lineNameHost = QtWidgets.QLineEdit(self.centralwidget)
        self.lineNameHost.setObjectName("lineNameHost")
        self.gridLayout_2.addWidget(self.lineNameHost, 4, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 507, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Настройки"))
        self.label_3.setText(_translate("MainWindow", "Имя пользователя"))
        self.label.setText(_translate("MainWindow", "Имя хоста"))
        self.label_2.setText(_translate("MainWindow", "Пароль"))
        self.label_4.setText(_translate("MainWindow", "Имя базы"))
        self.ConnectProverka.setText(_translate("MainWindow", "Проверка соединения"))
        self.SaveSetting.setText(_translate("MainWindow", "Сохранить настройки"))
        self.SelectRepository.setText(_translate("MainWindow", "Выбор репозитория"))
        self.radioButton.setText(_translate("MainWindow", "Показать пароль"))
